### ISSUE TITLE
[Feature request] Melding bij afronden opleiding/uitbreiding

### ISSUE THREAD

**Issue by CrustaShrimp** [JRH-1997/Scripts-MKS#57]
Op dit moment kan je wel zien hoe lang het nog duurt tot een opleiding is afgerond of een uitbreiding af is (zelfs al uitgerekend wanneer dit zal zijn, bijvoorbeeld Donderdag 17:31 ofzo), maar je wordt niet genotificeerd.
Als je veel uitbreidingen tegelijk doet raak je snel het overzicht kwijt en het zou fijn zijn om een notificatie te krijgen als iets is afgerond, zodat je weet dat je ermee aan de slag kunt.

Lastig punt is wel dat je op een of andere manier ook gevallen moet afvangen die zijn gebeurd terwijl je offline was.
Misschien iets met een notify lijstje op verloopdatum, na die verloopdatum (Donderdag 17:31) een notify geven en verwijderen uit het lijstje?

**Comment by JRH-1997** [comment]
Je kan in je meldkamer bij afrondingsgeschiedenis dit al zien. 
Die gegevens voor de uitbreidingen zijn alleen maar op de pagina van de uitbreiding en van de opleiding te zien. Maar niet makkelijk op te vragen zonder de server overmatig te belasten.
