### ISSUE TITLE
Run voor minimale bemanning

### ISSUE THREAD

**Issue by Rene-63** [JRH-1997/Scripts-MKS#67]
Is er een mogelijkheid om een optie in te bouwen waarbij in één keer alle voertuigen, die opgeleide bemanning nodig heeft, in te stellen met het minimaal aantal benodigde bemanningsleden?

Dus CO op 1, SB op 2, ME-AE op 6, enz.

Voordeel is dat dan niet meer opgeleide bemanning gekoppeld behoeft te worden en dat je het met het minimaal aantal benodigde opgeleide bemanningsleden kan doen.

**Comment by JRH-1997** [comment]
Gewoon die voertuigen af gaan in het dropdown menu en dan het minimum selecteren in het script voor de voertuiginstellingen wijzigen. Het is al heel makkelijk gemaakt,
