### ISSUE TITLE
US Police Supervisor / Sheriff Update

### ISSUE THREAD

**Issue by wgheath** [JRH-1997/Scripts-MKS#68]
It appears that there was an update to the vehicleChanges script a few months ago that I think is supposed to allow for updating the new Police Supervisor Auto Transport Settings.

To date, I have been unable to get those setting options to load.  Is there an update available that will allow access to update these new settings?

**Comment by JRH-1997** [comment]
That update is only done for the NL version because every version needs specific details to work. 
I need the vehicle ID's that do have these settings and I need the translations that are shown on the page of the vehicle settings for all these settings to set it up for the US version.

**Comment by wgheath** [comment]
Here is a snip from the vehicles v2 api for a police supervisor

{"id":4625367,"caption":"Police Supervisor / Sheriff Unit","building_id":2257878,"vehicle_type":47,"fms_real":2,"fms_show":2,"vehicle_type_caption":"","working_hour_start":0,"working_hour_end":0,"alarm_delay":0,"max_personnel_override":2,"ignore_aao":false,"tractive_vehicle_id":null,"assigned_personnel_count":2,"target_type":null,"target_id":null,"queued_mission_id":null,"image_url_static":"/images/vehicles/blue_car.png","image_url_animated":"/images/vehicles/blue_car_2.png","equipments":[]},

and a screen cap of the police supervisor/sheriff setting screen

![image](https://github.com/JRH-1997/Scripts-MKS/assets/5325719/3c5c5c4a-abc9-4080-a96f-3c00da29adf7)

Please let me know if there is anything else that you need.  Thank you!

**Comment by wgheath** [comment]
Possible values for Maximum fees are 0, 10, 20, 30 ,40, 50

Possible values for Max. Distance to Cell are 1, 5, 20, 50, 100, 200

Possible values for Cells to Leave Empty in Stations are 0 through 5

**Comment by JRH-1997** [comment]
I added it, I hope its in the background the same as the Dutch version. Please test if its working after updating the script on your pc.

**Comment by wgheath** [comment]
I have used the script to make multiple changes using different values each time and it appears that the script is working as it should.  Thank you very much for making that addition.
